### ISSUE TITLE
Slow performance with the custom blur brush

### ISSUE THREAD

**Issue by ArianMozafari** [EdiWang/Character-Map-UWP#31] opened 2018-11-01 08:57 UTC
The custom-made blur backdrop brush (it's a CompositionBrush I guess) brings a huge impact on the app's performance which results in a sluggish frame rate and a huge CPU usage for its kind (18% usage on a Core i7-4702MQ @ 2.20GHz). Also, the accent color fallback doesn't match the whole UI. Maybe one of the following methods solve the issue:
1. Using the fluent design's acrylic material instead of a custom-made brush
2. Removing the brush completely and using a solid color instead
3. Providing an option in the settings popup to disable the transparency and the fallback color
![annotationcm](https://user-images.githubusercontent.com/11410707/47842258-66f47400-ddd1-11e8-90e3-4c2ad6d7a6d4.png)

**Comment by JohnnyWestlake** [comment] 2018-11-01 22:30
Are you sure this is the brush causing it? Composition Brush (which is actually cheaper than acrylic) should be mostly using GPU power, not CPU, unless your machine can't use GPU.

**Comment by EdiWang** [comment] 2018-11-04 13:28
I've noticed a very bad performance issue on Windows 10 v1809, currently I don't have a root cause found. This may be related to the performance problem.

**Comment by ArianMozafari** [comment] 2018-11-10 13:39
Version 2018.5.1.0 brings a huge performance improvement with this updated design. The left sidebar still lags a bit sometimes but the app is performing way smoother (v1809 Build 17763.107). I also appreciate the design tweaks, the app interface looks super nice now!

**Comment by EdiWang** [comment] 2019-01-02 04:40
Fixed in v2018.6.0

**Closed by EdiWang** 2019-01-02 04:40 UTC
